
imagePullSecrets:
# - name: "image-pull-secret"
alertmanager:
  ingress:
    enabled: true
    annotations:
       kubernetes.io/ingress.class: nginx
       cert-manager.io/cluster-issuer: letsencrypt-staging
    hosts:
       - alertmanager.k8s.mehari.dev
    tls:
       - secretName: alertmgr-alerts-tls
         hosts:
           - alertmanager.k8s.mehari.dev
  persistentVolume:
    size: 2Gi
    # storageClass: "-"

server:
  ingress:
    enabled: true
    annotations:
       kubernetes.io/ingress.class: nginx
       cert-manager.io/cluster-issuer: letsencrypt-staging
    hosts:
       - prometheus.k8s.mehari.dev
    tls:
       - secretName: prometheus-alerts-tls
         hosts:
           - prometheus.k8s.mehari.dev
  persistentVolume:
    enabled: true
    size: 8Gi
    # storageClass: "-"
